[package]
name = "life_trick"
version = "0.2.0"
authors = ["Will McGloughlin <willem.mcg@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "0.3.4"
serde_json = "1.0.107"
lazy_static = "1.4.0"
rand = "0.8.5"